### ISSUE TITLE
expected the node content, but found '<stream end>'

### ISSUE THREAD

**Issue by semihural-tomtom** [karancode/yamllint-github-action#14]
What is the proper way of using `yamllint_config_datapath`

I am getting below error.

```
lint: info: yamllint on ..
invalid config: while parsing a flow node
expected the node content, but found '<stream end>'
  in "<unicode string>", line 1, column 10:
    {extends:
             ^
lint: error: failed yamllint on ..
```

Here is what I did

```
  linter:
    name: Lint org, sub-org and repository settings
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Yaml Lint
        uses: karancode/yamllint-github-action@c85ba571891f3a9571b9bb89a7e31d099f4fd4a1
        with:
          yamllint_config_datapath: '{extends: "relaxed", rules: "{line-length: {max: 120}}"}'
          yamllint_strict: false
          yamllint_comment: true
```
